### ISSUE TITLE
Upgrade to null-safety Error

### ISSUE THREAD

**Issue by xiaosongmao123** [rulila52/adaptive-scrollbar#1]
Thanks for developing this amazing plug

``````
[0.1.4] - 11.05.2021 #
Upgrade to null-safety.
``````

Please update the source code，**but by now it's not null-safety**!!!

you need update the code adaptive_scrollbar.dart ,

by [0.1.4] - 11.05.2021 only updated the pubspec.yaml Nothing was actually done

``````
Widget child;

to

Widget? child;
``````

**Comment by rulila52** [comment]
Thank you for your issue, I published this version by mistake, noticed it almost immediately and did not have time to fix it. Now i posted a new version that should support null-safety
